// Generated by CoffeeScript 1.7.1
var jsdom, request, request_options;

request = require('request');

jsdom = require('jsdom');

request_options = {
  'headers': {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Safari/537.36'
  }
};

module.exports.prepare = function(url, callback) {
  request_options.url = url;
  return request(request_options, function(error, response, body) {
    var document, window;
    document = jsdom.jsdom(body, null, {
      'features': {
        'SkipExternalResources': /(cloudfront|google|yadro|addthis|facebook|youtube)/,
        'FetchExternalResources': false,
        'ProcessExternalResources': false
      }
    });
    window = document.parentWindow;
    return jsdom.jQueryify(window, "http://code.jquery.com/jquery.js", function() {
      return callback(null, window);
    });
  });
};
